path: /tmp/databases/ycb-video/YCB_Video_Dataset
train: /tmp/databases/ycb-video/YCB_Video_Dataset/train.txt
val: /tmp/databases/ycb-video/YCB_Video_Dataset/val.txt

names: 
  0: 002_master_chef_can
  1: 003_cracker_box
  2: 004_sugar_box
  3: 005_tomato_soup_can
  4: 006_mustard_bottle
  5: 007_tuna_fish_can
  6: 008_pudding_box
  7: 009_gelatin_box
  8: 010_potted_meat_can
  9: 011_banana
  10: 019_pitcher_base
  11: 021_bleach_cleanser
  12: 024_bowl
  13: 025_mug
  14: 035_power_drill
  15: 036_wood_block
  16: 037_scissors
  17: 040_large_marker
  18: 051_large_clamp
  19: 052_extra_large_clamp
  20: 061_foam_brick
